# Generated by Django 3.1 on 2020-08-12 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[('student', '学生'), ('teacher', '老师')], default='学生', max_length=32),
        ),
    ]
