# Generated by Django 3.1 on 2020-08-13 19:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backstage', '0005_auto_20200813_1941'),
        ('login', '0002_user_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='to_class',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='backstage.class'),
            preserve_default=False,
        ),
    ]
