# Generated by Django 3.1 on 2020-08-13 23:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backstage', '0005_auto_20200813_1941'),
        ('login', '0004_auto_20200813_2319'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('password', models.CharField(max_length=256)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('sex', models.CharField(choices=[('male', '男'), ('female', '女')], default='男', max_length=32)),
                ('status', models.CharField(choices=[('student', '学生'), ('teacher', '老师')], default='学生', max_length=32)),
                ('c_time', models.DateTimeField(auto_now_add=True)),
                ('to_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backstage.class')),
            ],
            options={
                'verbose_name': '用户',
                'verbose_name_plural': '用户',
                'ordering': ['c_time'],
            },
        ),
        migrations.DeleteModel(
            name='Student',
        ),
    ]
