# Generated by Django 3.1 on 2020-08-13 23:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backstage', '0005_auto_20200813_1941'),
        ('login', '0006_auto_20200813_2329'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='status',
            field=models.CharField(default='学生', editable=False, max_length=10),
        ),
        migrations.AddField(
            model_name='teacher',
            name='status',
            field=models.CharField(default='老师', editable=False, max_length=10),
        ),
        migrations.AlterField(
            model_name='student',
            name='to_class',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='backstage.class'),
        ),
    ]
