# Generated by Django 3.1 on 2020-08-14 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0008_teacher_own_class'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='own_class',
        ),
    ]
