# Generated by Django 3.1 on 2020-08-14 11:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backstage', '0006_class_create_teacher'),
        ('login', '0009_remove_teacher_own_class'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='to_class',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='backstage.class'),
        ),
    ]
