# Generated by Django 3.1 on 2020-08-14 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0011_auto_20200814_1416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='status',
            field=models.CharField(default='学生', editable=False, max_length=10, null=True),
        ),
    ]
