# Generated by Django 3.1 on 2020-08-14 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blog_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'ordering': ['c_time'], 'verbose_name': '博客', 'verbose_name_plural': '博客'},
        ),
    ]
