# Generated by Django 3.1 on 2020-08-14 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20200814_2134'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='author',
            new_name='作者',
        ),
        migrations.RenameField(
            model_name='blog',
            old_name='title',
            new_name='标题',
        ),
    ]
