# Generated by Django 3.1 on 2020-08-14 21:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20200814_2135'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='标题',
            new_name='title',
        ),
    ]
