# Generated by Django 3.1 on 2020-08-14 21:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20200814_2137'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='作者',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='blog',
            old_name='内容',
            new_name='context',
        ),
        migrations.RenameField(
            model_name='blog',
            old_name='点赞数',
            new_name='zan_num',
        ),
    ]
