# Generated by Django 3.1 on 2020-08-23 10:39

from django.db import migrations, models
import mdeditor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20200814_2157'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='文章编号')),
                ('title', models.CharField(max_length=50, verbose_name='文章标题')),
                ('content', mdeditor.fields.MDTextField()),
                ('publish_time', models.DateTimeField(auto_now_add=True, verbose_name='发表时间')),
                ('last_update_time', models.DateTimeField(auto_now=True, verbose_name='最后一次修改时间')),
                ('read_count', models.IntegerField(default=0, verbose_name='阅读次数')),
                ('comment_count', models.IntegerField(default=0, verbose_name='评论次数')),
            ],
        ),
        migrations.RemoveField(
            model_name='blog',
            name='class_choice',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='context',
        ),
        migrations.AddField(
            model_name='blog',
            name='comment_count',
            field=models.IntegerField(default=0, verbose_name='评论次数'),
        ),
        migrations.AddField(
            model_name='blog',
            name='content',
            field=mdeditor.fields.MDTextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blog',
            name='read_count',
            field=models.IntegerField(default=0, verbose_name='阅读次数'),
        ),
    ]
