# Generated by Django 3.1 on 2020-08-23 10:43

from django.db import migrations, models
import django.utils.timezone
import mdeditor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20200823_1039'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'ordering': ['publish_time'], 'verbose_name': '博客', 'verbose_name_plural': '博客'},
        ),
        migrations.RemoveField(
            model_name='blog',
            name='c_time',
        ),
        migrations.AddField(
            model_name='blog',
            name='last_update_time',
            field=models.DateTimeField(auto_now=True, verbose_name='最后一次修改时间'),
        ),
        migrations.AddField(
            model_name='blog',
            name='publish_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='发表时间'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='article',
            name='content',
            field=mdeditor.fields.MDTextField(default=None),
        ),
    ]
