# Generated by Django 3.1 on 2020-08-23 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20200823_1043'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Article',
        ),
        migrations.AlterField(
            model_name='blog',
            name='zan_num',
            field=models.IntegerField(default=0, verbose_name='点赞次数'),
        ),
    ]
