# Generated by Django 3.1 on 2020-08-12 23:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backstage', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['c_time'], 'verbose_name': '任务'},
        ),
        migrations.AlterModelTable(
            name='task',
            table='task',
        ),
    ]
