# Generated by Django 3.1 on 2020-08-13 00:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backstage', '0002_auto_20200812_2354'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['c_time'], 'verbose_name': '任务', 'verbose_name_plural': '任务'},
        ),
    ]
