# Generated by Django 3.1 on 2020-08-13 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backstage', '0004_class'),
    ]

    operations = [
        migrations.RenameField(
            model_name='class',
            old_name='max_num',
            new_name='max_student',
        ),
    ]
