# Generated by Django 3.1 on 2020-08-14 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backstage', '0005_auto_20200813_1941'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='create_teacher',
            field=models.CharField(default=None, max_length=10),
        ),
    ]
