# Generated by Django 3.1 on 2020-08-14 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backstage', '0006_class_create_teacher'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='class',
            name='max_student',
        ),
    ]
